USE zomatodb;
Select* from customer;
select* from foods;
select* from order_detail;
select* from order_food;
select* from payment_table;
select * from restaurant;
select* from zomato_employee;

-- --Top 3 customers who have placed the highest number of orders. -----------------------------------
Select c.customer_id,c.customer_name,COUNT(ofd.orderF_id) as total_orders from customer c 
join order_food as ofd ON c.customer_id= ofd.customer_id 
group by c.customer_id,c.customer_name order by total_orders  DESC limit 3;

-- Find the restaurant that has received the highest average rating.-------------------------------------------
select restaurant_id,restaurant_name,rlocation,avg(rrating) as average_rating from restaurant
group by restaurant_name,rlocation,restaurant_id order by average_rating desc limit 1;

-- List all orders from order_detail that were delivered in under 30 minutes.---------------
SELECT order_id,order_status,order_time,delivered_time,
TIMESTAMPDIFF(MINUTE, order_time, delivered_time) AS delivery_minutes
FROM order_detail WHERE TIMESTAMPDIFF(MINUTE, order_time, delivered_time) < 30;

-- Calculate the total revenue generated by each food item. Display food_id, food_name and Total revenue ordered by total revenue in descending order.
SELECT f.food_id,f.food_name,SUM(f.price_per_unit * quantity) AS total_revenue
FROM foods f JOIN order_food ON f.food_id = order_food.food_id
GROUP BY f.food_id, f.food_name ORDER BY total_revenue DESC;

-- Find the second highest revenue-generating restaurant.-------------------------
SELECT r.restaurant_id,r.restaurant_name,SUM(f.price_per_unit *  ofd.quantity) AS total_revenue FROM restaurant r
JOIN foods f ON r.restaurant_id = f.restaurant_id JOIN order_food ofd ON f.food_id = ofd.food_id
GROUP BY r.restaurant_id, r.restaurant_name ORDER BY total_revenue DESC LIMIT 1 OFFSET 1;

-- Find the 5 most popular food items based on the quantity sold. --------------------------------------------
SELECT f.food_id,f.food_name,SUM(ofd.quantity) AS total_quantity_sold FROM order_food ofd
JOIN foods f ON ofd.food_id = f.food_id
GROUP BY f.food_id, f.food_name ORDER BY total_quantity_sold DESC LIMIT 5;

-- List the top 3 Zomato employees with the highest average delivery ratings. --------------------------------
SELECT employee_id,employee_name from zomato_employee order by employee_avg_rating desc limit 3 ;

-- Determine the month with the highest number of total orders placed ------------------------------------------
SELECT MONTH(order_time) AS month_no,MONTHNAME(order_time) AS month_name,COUNT(*) AS total_orders FROM order_detail
GROUP BY MONTH(order_time), MONTHNAME(order_time) ORDER BY total_orders DESC LIMIT 1;

-- Calculate the average order amount for each customer. Order by average order amount in descending order. -------
SELECT c.customer_id,c.customer_name,AVG(order_total) AS avg_order_amount FROM customer c
JOIN (
    SELECT ofd.order_id,ofd.customer_id,SUM(ofd.quantity * f.price_per_unit) AS order_total
    FROM order_food ofd JOIN foods f ON ofd.food_id = f.food_id
    GROUP BY ofd.order_id, ofd.customer_id
) t ON c.customer_id = t.customer_id
GROUP BY c.customer_id, c.customer_name ORDER BY avg_order_amount DESC;

-- Identify the most frequent customer for each restaurant.---------------------------------------------------------
SELECT restaurant_id,customer_id,COUNT(*) AS total_orders FROM order_detail
GROUP BY restaurant_id, customer_id ORDER BY total_orders DESC;

-- Calculate the total number of orders placed on weekends. --------------------------------------------------------
SELECT COUNT(*) AS weekend_orders FROM order_detail
WHERE DAYOFWEEK(order_time) IN (1,7);

-- Calculate the average delivery time (in minutes) for orders placed on weekdays versus weekends.------------------
SELECT
    CASE
        WHEN DAYOFWEEK(order_time) IN (1,7)
        THEN 'Weekend'
        ELSE 'Weekday'
    END AS day_type,
    AVG(TIMESTAMPDIFF(MINUTE, order_time, delivered_time))
    AS avg_delivery_time
FROM order_detail
GROUP BY day_type;

--  List the top 5 most expensive food items. Display food_id, food_name, and price_per_unit for all food items with the highest 5 prices. 
SELECT food_id,food_name,price_per_unit FROM foods ORDER BY price_per_unit DESC LIMIT 5;

-- Find the restaurant with the most diverse menu (i.e., the highest number of food items)--------------------------
SELECT r.restaurant_id,r.restaurant_name,COUNT(DISTINCT ofd.food_id) AS total_food_items
FROM restaurant r JOIN order_food ofd ON r.restaurant_id = ofd.restaurant_id
GROUP BY r.restaurant_id, r.restaurant_name ORDER BY total_food_items DESC LIMIT 1;

--  Calculate total payment amount for each payment type. ---------------------------------------------------------
SELECT p.payment_type,SUM(ofd.quantity * f.price_per_unit) AS total_payment_amount
FROM payment_table p
JOIN order_food ofd ON p.order_id = ofd.order_id
JOIN foods f ON ofd.food_id = f.food_id GROUP BY p.payment_type;



